/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BRENO
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(177, 179, 158));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        wrapperPanel = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        menuBtn6 = new javax.swing.JButton();
        menuBtn5 = new javax.swing.JButton();
        menuBtn2 = new javax.swing.JButton();
        menuBtn4 = new javax.swing.JButton();
        menuBtn3 = new javax.swing.JButton();
        menuBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 1 (1).png"))); // NOI18N
        getContentPane().add(logo, java.awt.BorderLayout.NORTH);

        wrapperPanel.setOpaque(false);
        wrapperPanel.setLayout(new java.awt.GridBagLayout());

        menu.setBackground(new java.awt.Color(177, 179, 158));
        menu.setOpaque(false);
        menu.setPreferredSize(new java.awt.Dimension(630, 255));
        menu.setLayout(new java.awt.GridLayout(2, 3, 30, 30));

        menuBtn6.setText("GLOSSARIO");
        menuBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtn6ActionPerformed(evt);
            }
        });
        menu.add(menuBtn6);

        menuBtn5.setText("AGENDA");
        menuBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtn5ActionPerformed(evt);
            }
        });
        menu.add(menuBtn5);

        menuBtn2.setText("AGENDA");
        menuBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtn2ActionPerformed(evt);
            }
        });
        menu.add(menuBtn2);

        menuBtn4.setText("GLOSSARIO");
        menuBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtn4ActionPerformed(evt);
            }
        });
        menu.add(menuBtn4);

        menuBtn3.setText("GLOSSARIO");
        menuBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtn3ActionPerformed(evt);
            }
        });
        menu.add(menuBtn3);

        menuBtn1.setText("GLOSSARIO");
        menuBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtn1ActionPerformed(evt);
            }
        });
        menu.add(menuBtn1);

        wrapperPanel.add(menu, new java.awt.GridBagConstraints());

        getContentPane().add(wrapperPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn1ActionPerformed

    private void menuBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn2ActionPerformed

    private void menuBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn3ActionPerformed

    private void menuBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn4ActionPerformed

    private void menuBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn5ActionPerformed

    private void menuBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menuBtn1;
    private javax.swing.JButton menuBtn2;
    private javax.swing.JButton menuBtn3;
    private javax.swing.JButton menuBtn4;
    private javax.swing.JButton menuBtn5;
    private javax.swing.JButton menuBtn6;
    private javax.swing.JPanel wrapperPanel;
    // End of variables declaration//GEN-END:variables
}
